const IF_DATA = {

  muscleGroups: [
    { id:'chest', ar:'صدر', en:'Chest' },
    { id:'back', ar:'ظهر', en:'Back' },
    { id:'legs', ar:'رجل', en:'Legs' },
    { id:'shoulders', ar:'كتف', en:'Shoulders' },
    { id:'arms', ar:'ذراعين', en:'Arms' },
    { id:'core', ar:'بطن وكور', en:'Core' },
    { id:'cardio', ar:'كارديو', en:'Cardio' },
  ],

  categories: {
    strength: { ar:'قوة', en:'Strength' },
    cardio:   { ar:'كارديو', en:'Cardio' },
    isometry: { ar:'ثبات', en:'Isometric' },
  },

  exercises: [
    { id:'bench-press', muscle:'chest', level:'medium', equip:'barbell', pattern:'push',
      cat:'strength', sets:'3–4', reps:'6–10',
      targets:[{ar:'الصدر',en:'Chest'},{ar:'الترايسبس',en:'Triceps'},{ar:'الكتف الأمامي',en:'Front Delts'}],
      ar:'بنش برس بار', en:'Barbell Bench Press',
      descAr:'تمرين أساسي لبناء الصدر والترايسبس والكتف الأمامي.',
      descEn:'A core compound lift for chest, triceps and front delts.',
      stepsAr:['استلقِ على البنش وقدماك ثابتة على الأرض','امسك البار بمسافة أعرض من الكتف قليلًا','انزل البار لمنتصف الصدر بشكل متحكم','ادفع البار لأعلى حتى قفل الذراعين بدون قفل مفاجئ للمرفق'],
      stepsEn:['Lie on the bench with feet flat on the floor','Grip the bar slightly wider than shoulder width','Lower the bar to mid-chest under control','Press up until arms extend without locking out hard'],
      mistakesAr:'أخطاء شائعة: رفع الحوض عن البنش، وارتداد البار عن الصدر.',
      mistakesEn:'Common mistakes: hips lifting off the bench, bouncing the bar off the chest.',
      breathAr:'خُذ شهيق عميق وأنت تنزل البار، وأخرج الزفير تدريجيًا مع الدفع لأعلى.',
      breathEn:'Inhale deeply as you lower the bar, exhale gradually as you press up.',
      altAr:'بديل بدون جهاز: ضغط بالدمبل أو ضغط أرضي (Push-up).',
      altEn:'No-equipment alt: dumbbell press or push-ups.' },

    { id:'incline-db-press', muscle:'chest', level:'medium', equip:'dumbbell', pattern:'push',
      cat:'strength', sets:'3', reps:'8–12',
      targets:[{ar:'الصدر العلوي',en:'Upper Chest'},{ar:'الكتف الأمامي',en:'Front Delts'},{ar:'الترايسبس',en:'Triceps'}],
      ar:'بنش مائل دمبل', en:'Incline Dumbbell Press',
      descAr:'يركّز على الجزء العلوي من الصدر.',
      descEn:'Targets the upper chest.',
      stepsAr:['اضبط البنش على زاوية 30-45 درجة','ادفع الدمبلز لأعلى فوق الصدر العلوي','انزل ببطء حتى تشعر بتمدد خفيف'],
      stepsEn:['Set the bench to 30–45 degrees','Press the dumbbells above the upper chest','Lower slowly until a light stretch'],
      mistakesAr:'زاوية عالية جدًا تحوّل الحمل للكتف بدل الصدر.',
      mistakesEn:'Too steep an angle shifts load to the shoulders.',
      breathAr:'شهيق مع النزول بتحكم، وزفير قوي مع الدفع لأعلى.',
      breathEn:'Inhale on the way down under control, exhale forcefully as you press.',
      altAr:'بديل: بنش مائل بار.', altEn:'Alt: incline barbell press.' },

    { id:'pushup', muscle:'chest', level:'easy', equip:'none', pattern:'push',
      cat:'strength', sets:'3', reps:'10–15',
      targets:[{ar:'الصدر',en:'Chest'},{ar:'الترايسبس',en:'Triceps'},{ar:'الكور',en:'Core'}],
      ar:'ضغط أرضي', en:'Push-Up',
      descAr:'تمرين وزن جسم ممتاز للصدر والترايسبس والكور.',
      descEn:'A great bodyweight move for chest, triceps and core.',
      stepsAr:['ابدأ بوضع اللوح الخشبي، اليدين أعرض من الكتف قليلًا','انزل جسمك لأسفل بشكل مستقيم','ادفع لأعلى حتى تمديد كامل للذراعين'],
      stepsEn:['Start in a plank, hands slightly wider than shoulders','Lower your body in a straight line','Push back up to full extension'],
      mistakesAr:'ارتخاء الحوض للأسفل أثناء الحركة.',
      mistakesEn:'Letting the hips sag during the movement.',
      breathAr:'شهيق أثناء النزول، وزفير أثناء الدفع لأعلى.',
      breathEn:'Inhale as you lower, exhale as you push up.',
      altAr:'أسهل: ضغط على الركب. أصعب: ضغط مرتفع الأرجل.',
      altEn:'Easier: knee push-ups. Harder: feet-elevated push-ups.' },

    { id:'lat-pulldown', muscle:'back', level:'easy', equip:'machine', pattern:'pull',
      cat:'strength', sets:'3', reps:'10–12',
      targets:[{ar:'اللاتس (عرض الظهر)',en:'Lats'},{ar:'الظهر العلوي',en:'Upper Back'},{ar:'البايسبس',en:'Biceps'}],
      ar:'سحب أمامي', en:'Lat Pulldown',
      descAr:'يبني عرض الظهر (اللاتس).',
      descEn:'Builds back width (lats).',
      stepsAr:['امسك البار بمسافة أوسع من الكتف','اسحب البار لأعلى الصدر مع فرد الصدر للأمام','ارجع ببطء للأعلى بدون فقدان التحكم'],
      stepsEn:['Grip the bar wider than shoulder width','Pull the bar to your upper chest, chest up','Return slowly with control'],
      mistakesAr:'الاعتماد على ارتداد الجسم للخلف بدل عضلة الظهر.',
      mistakesEn:'Relying on leaning back instead of the lats.',
      breathAr:'زفير مع السحب للأسفل، وشهيق مع العودة للأعلى ببطء.',
      breathEn:'Exhale pulling down, inhale slowly on the way back up.',
      altAr:'بديل بدون جهاز: عقلة (Pull-up) أو سحب بمقاومة مطاطية.',
      altEn:'No-machine alt: pull-ups or band pull-downs.' },

    { id:'deadlift', muscle:'back', level:'hard', equip:'barbell', pattern:'hinge',
      cat:'strength', sets:'4', reps:'4–6',
      targets:[{ar:'أوتار الركبة',en:'Hamstrings'},{ar:'أسفل الظهر',en:'Lower Back'},{ar:'المؤخرة',en:'Glutes'}],
      ar:'ديدليفت', en:'Deadlift',
      descAr:'من أقوى تمارين الجسم الكامل، يبني الظهر والرجل والقوة العامة.',
      descEn:'One of the best full-body lifts for back, legs and overall strength.',
      stepsAr:['قف والبار فوق منتصف القدم','امسك البار وظهرك مستقيم والصدر مرفوع','ادفع بالأرض بقدميك وارفع البار قريب من الجسم'],
      stepsEn:['Stand with the bar over mid-foot','Grip the bar, back straight, chest up','Push through the floor and lift, bar close to the body'],
      mistakesAr:'تقويس الظهر السفلي، والبار بعيد عن الجسم.',
      mistakesEn:'Rounding the lower back, bar drifting away from the body.',
      breathAr:'شهيق وحبس النفس خفيف قبل الرفع (بريسيور)، وزفير بعد تجاوز أصعب نقطة.',
      breathEn:'Big inhale and light brace before lifting, exhale past the sticking point.',
      altAr:'بديل أسهل: ديدليفت رومانى بدمبل.', altEn:'Easier alt: dumbbell Romanian deadlift.' },

    { id:'bent-row', muscle:'back', level:'medium', equip:'barbell', pattern:'pull',
      cat:'strength', sets:'4', reps:'8–12',
      targets:[{ar:'الظهر العلوي',en:'Upper Back'},{ar:'اللاتس',en:'Lats'},{ar:'البايسبس',en:'Biceps'}],
      ar:'سحب بار منحني', en:'Bent-Over Barbell Row',
      descAr:'يبني سماكة الظهر.',
      descEn:'Builds back thickness.',
      stepsAr:['انحنِ للأمام مع ثني بسيط بالركبة وظهر مستقيم','اسحب البار تجاه أسفل الصدر','انزل ببطء بدون فقدان استقامة الظهر'],
      stepsEn:['Hinge forward, slight knee bend, back straight','Pull the bar toward your lower chest','Lower slowly keeping the back straight'],
      mistakesAr:'تحديب الظهر أثناء السحب.',
      mistakesEn:'Rounding the back during the pull.',
      breathAr:'زفير مع سحب البار للجسم، وشهيق مع النزول بتحكم.',
      breathEn:'Exhale pulling the bar in, inhale lowering with control.',
      altAr:'بديل: سحب دمبل بيد واحدة.', altEn:'Alt: single-arm dumbbell row.' },

    { id:'squat', muscle:'legs', level:'hard', equip:'barbell', pattern:'squat',
      cat:'strength', sets:'4', reps:'6–10',
      targets:[{ar:'الكوادريسبس',en:'Quads'},{ar:'المؤخرة',en:'Glutes'},{ar:'الكور',en:'Core'}],
      ar:'سكوات بار', en:'Barbell Squat',
      descAr:'ملك تمارين الرجل، يبني الكواد والمؤخرة والقوة العامة.',
      descEn:'The king of leg exercises — builds quads, glutes and overall strength.',
      stepsAr:['ضع البار على الترابيس العلوي','انزل بالحوض للخلف والأسفل مع بقاء الصدر مرفوع','انزل حتى الفخذ موازي للأرض ثم ادفع للأعلى'],
      stepsEn:['Rest the bar on your upper traps','Push hips back and down, chest up','Descend to thigh-parallel then drive back up'],
      mistakesAr:'انهيار الركبتين للداخل، ورفع الكعبين عن الأرض.',
      mistakesEn:'Knees caving inward, heels lifting off the ground.',
      breathAr:'شهيق عميق قبل النزول، وزفير قوي أثناء الدفع للصعود.',
      breathEn:'Deep inhale before descending, strong exhale driving back up.',
      altAr:'بديل بدون جهاز: سكوات وزن جسم أو سكوات بلغاري.',
      altEn:'No-equipment alt: bodyweight squat or Bulgarian split squat.' },

    { id:'lunges', muscle:'legs', level:'easy', equip:'none', pattern:'squat',
      cat:'strength', sets:'3', reps:'10–12 / رجل',
      targets:[{ar:'الكوادريسبس',en:'Quads'},{ar:'المؤخرة',en:'Glutes'},{ar:'أوتار الركبة',en:'Hamstrings'}],
      ar:'لنجز', en:'Lunges',
      descAr:'يبني الكواد والمؤخرة ويحسن التوازن.',
      descEn:'Builds quads and glutes while improving balance.',
      stepsAr:['خطوة للأمام بقدم واحدة','انزل حتى الركبة الخلفية تقترب من الأرض','ادفع بالقدم الأمامية للرجوع للوقوف'],
      stepsEn:['Step forward with one leg','Lower until the back knee nears the floor','Push through the front foot to return'],
      mistakesAr:'الركبة الأمامية تتخطى أصابع القدم بشكل مبالغ.',
      mistakesEn:'Front knee traveling too far past the toes.',
      breathAr:'شهيق مع النزول، وزفير مع الدفع والرجوع للوقوف.',
      breathEn:'Inhale descending, exhale pushing back to standing.',
      altAr:'أصعب: لنجز بدمبل.', altEn:'Harder: weighted lunges with dumbbells.' },

    { id:'leg-press', muscle:'legs', level:'easy', equip:'machine', pattern:'squat',
      cat:'strength', sets:'3', reps:'10–12',
      targets:[{ar:'الكوادريسبس',en:'Quads'},{ar:'المؤخرة',en:'Glutes'}],
      ar:'ليج برس', en:'Leg Press',
      descAr:'بديل آمن نسبيًا للسكوات لبناء الرجل.',
      descEn:'A relatively safe squat alternative for leg development.',
      stepsAr:['ضع قدميك بعرض الكتف على المنصة','انزل حتى زاوية 90 درجة بالركبة','ادفع بدون قفل كامل للركبة في الأعلى'],
      stepsEn:['Place feet shoulder-width on the platform','Lower to a 90-degree knee angle','Press up without locking the knees fully'],
      mistakesAr:'رفع أسفل الظهر عن المقعد.',
      mistakesEn:'Lower back lifting off the seat.',
      breathAr:'شهيق مع نزول المنصة، وزفير مع الضغط للأمام.',
      breathEn:'Inhale as the platform lowers, exhale pressing away.',
      altAr:'بديل: سكوات جوبلت بدمبل.', altEn:'Alt: goblet squat with a dumbbell.' },

    { id:'ohp', muscle:'shoulders', level:'medium', equip:'barbell', pattern:'press',
      cat:'strength', sets:'3', reps:'6–10',
      targets:[{ar:'الكتف الأمامي',en:'Front Delts'},{ar:'الكتف الجانبي',en:'Side Delts'},{ar:'الترايسبس',en:'Triceps'}],
      ar:'برس كتف واقف', en:'Overhead Press',
      descAr:'يبني الكتف الأمامي والجانبي وقوة الجزء العلوي.',
      descEn:'Builds front/side delts and upper-body strength.',
      stepsAr:['امسك البار عند مستوى الكتف','ادفع البار لأعلى حتى تمديد كامل للذراعين','انزل ببطء لنقطة البداية'],
      stepsEn:['Hold the bar at shoulder level','Press overhead to full extension','Lower slowly to the start'],
      mistakesAr:'تقويس أسفل الظهر أثناء الدفع.',
      mistakesEn:'Overarching the lower back during the press.',
      breathAr:'شهيق قبل الدفع، وزفير مع تمرير أصعب نقطة في الأعلى.',
      breathEn:'Inhale before pressing, exhale through the top half.',
      altAr:'بديل: برس دمبل جالس.', altEn:'Alt: seated dumbbell press.' },

    { id:'lateral-raise', muscle:'shoulders', level:'easy', equip:'dumbbell', pattern:'press',
      cat:'strength', sets:'3', reps:'12–15',
      targets:[{ar:'الكتف الجانبي',en:'Side Delts'}],
      ar:'رفرفة جانبية', en:'Lateral Raise',
      descAr:'يبني عرض الكتف (الجزء الجانبي).',
      descEn:'Builds shoulder width (side delts).',
      stepsAr:['امسك دمبل بكل يد بجانب الجسم','ارفع الذراعين جانبيًا حتى مستوى الكتف','انزل ببطء وتحكم'],
      stepsEn:['Hold a dumbbell in each hand by your sides','Raise arms out to shoulder height','Lower slowly with control'],
      mistakesAr:'استخدام ارتداد الجسم بدل عضلة الكتف.',
      mistakesEn:'Using body momentum instead of the delts.',
      breathAr:'زفير مع الرفرفة لأعلى، وشهيق مع النزول البطيء.',
      breathEn:'Exhale raising up, inhale lowering slowly.',
      altAr:'بديل: رفرفة بمقاومة مطاطية.', altEn:'Alt: resistance band lateral raise.' },

    { id:'barbell-curl', muscle:'arms', level:'easy', equip:'barbell', pattern:'curl',
      cat:'strength', sets:'3', reps:'8–12',
      targets:[{ar:'البايسبس',en:'Biceps'},{ar:'الساعد',en:'Forearms'}],
      ar:'بايسبس بار', en:'Barbell Curl',
      descAr:'تمرين أساسي لبناء البايسبس.',
      descEn:'A core biceps builder.',
      stepsAr:['امسك البار بقبضة تحتية بعرض الكتف','ارفع البار لأعلى مع تثبيت المرفقين','انزل ببطء وتحكم'],
      stepsEn:['Underhand grip, shoulder-width','Curl the bar up keeping elbows fixed','Lower slowly with control'],
      mistakesAr:'تأرجح الجسم للخلف والأمام لمساعدة الرفع.',
      mistakesEn:'Swinging the body to assist the lift.',
      breathAr:'زفير مع ثني البار لأعلى، وشهيق مع النزول بتحكم.',
      breathEn:'Exhale curling up, inhale lowering under control.',
      altAr:'بديل: بايسبس دمبل بالتبادل.', altEn:'Alt: alternating dumbbell curls.' },

    { id:'tricep-pushdown', muscle:'arms', level:'easy', equip:'cable', pattern:'push',
      cat:'strength', sets:'3', reps:'10–15',
      targets:[{ar:'الترايسبس',en:'Triceps'}],
      ar:'ترايسبس كابل', en:'Triceps Pushdown',
      descAr:'يبني الترايسبس بشكل معزول.',
      descEn:'Isolates the triceps.',
      stepsAr:['امسك الحبل أو البار من جهاز الكابل','ادفع للأسفل حتى تمديد كامل للذراع','ارجع ببطء بدون تحريك المرفقين'],
      stepsEn:['Grip the rope or bar attachment','Push down to full extension','Return slowly, elbows fixed'],
      mistakesAr:'تحريك المرفقين للأمام والخلف.',
      mistakesEn:'Elbows drifting forward and back.',
      breathAr:'زفير مع الدفع للأسفل، وشهيق مع العودة ببطء.',
      breathEn:'Exhale pushing down, inhale returning slowly.',
      altAr:'بديل: ديبس على مقعدين.', altEn:'Alt: bench dips.' },

    { id:'plank', muscle:'core', level:'easy', equip:'none', pattern:'core',
      cat:'isometry', sets:'3', reps:'30–60 ثانية',
      targets:[{ar:'الكور العميق',en:'Deep Core'},{ar:'البطن',en:'Abs'}],
      ar:'بلانك', en:'Plank',
      descAr:'تمرين ثبات ممتاز لعضلات البطن العميقة.',
      descEn:'An excellent isometric move for deep core muscles.',
      stepsAr:['استلقِ على المرفقين وأطراف أصابع القدم','حافظ على جسم مستقيم من الرأس للكعبين','ثبّت الوضعية للمدة المطلوبة'],
      stepsEn:['Rest on forearms and toes','Keep a straight line from head to heels','Hold for the target duration'],
      mistakesAr:'ارتفاع أو هبوط الحوض عن الخط المستقيم.',
      mistakesEn:'Hips sagging or piking out of line.',
      breathAr:'تنفس هادئ ومتصل من الأنف — لا تحبس نفسك أثناء الثبات.',
      breathEn:'Keep calm continuous breathing — never hold your breath while holding.',
      altAr:'أسهل: بلانك على الركب.', altEn:'Easier: knee plank.' },

    { id:'crunches', muscle:'core', level:'easy', equip:'none', pattern:'core',
      cat:'strength', sets:'3', reps:'15–20',
      targets:[{ar:'البطن العلوية',en:'Upper Abs'}],
      ar:'كرانشز', en:'Crunches',
      descAr:'تمرين كلاسيكي لعضلات البطن العلوية.',
      descEn:'A classic move for the upper abs.',
      stepsAr:['استلقِ وثنِ ركبتيك وقدميك على الأرض','ارفع الجزء العلوي من الجسم بانقباض البطن','انزل ببطء بدون فرد الرقبة'],
      stepsEn:['Lie down, knees bent, feet flat','Curl the upper body up using the abs','Lower slowly without straining the neck'],
      mistakesAr:'شد الرقبة باليدين أثناء الرفع.',
      mistakesEn:'Pulling the neck with the hands.',
      breathAr:'زفير مع الانقباض لأعلى، وشهيق مع النزول.',
      breathEn:'Exhale crunching up, inhale lowering down.',
      altAr:'أصعب: كرانش بعجلة أو كيبل.', altEn:'Harder: ab wheel or cable crunch.' },

    { id:'treadmill', muscle:'cardio', level:'easy', equip:'machine', pattern:'cardio',
      cat:'cardio', sets:'—', reps:'15–30 دقيقة',
      targets:[{ar:'القلب والرئتين',en:'Heart & Lungs'},{ar:'الرجل',en:'Legs'}],
      ar:'جري على السير', en:'Treadmill Running',
      descAr:'كارديو أساسي لحرق السعرات وتحسين اللياقة القلبية.',
      descEn:'A staple cardio move for calorie burn and cardio fitness.',
      stepsAr:['ابدأ بمشي سريع للإحماء 5 دقائق','ارفع السرعة تدريجيًا للجري','برّد الجسم بمشي بطيء آخر 5 دقائق'],
      stepsEn:['Start with a 5-min brisk walk warm-up','Gradually increase speed to a run','Cool down with a 5-min slow walk'],
      mistakesAr:'الإمساك بحواف الجهاز أثناء الجري.',
      mistakesEn:'Gripping the handrails while running.',
      breathAr:'تنفس إيقاعي من الأنف والفم معًا — مثلاً شهيق خطوتين وزفير خطوتين.',
      breathEn:'Rhythmic breathing through nose and mouth — e.g. inhale 2 steps, exhale 2 steps.',
      altAr:'بديل بدون جهاز: جري في الهواء الطلق أو نط الحبل.',
      altEn:'No-equipment alt: outdoor running or jump rope.' },

    { id:'jump-rope', muscle:'cardio', level:'medium', equip:'none', pattern:'cardio',
      cat:'cardio', sets:'—', reps:'3–5 × دقيقة',
      targets:[{ar:'القلب والرئتين',en:'Heart & Lungs'},{ar:'السمانة',en:'Calves'}],
      ar:'نط الحبل', en:'Jump Rope',
      descAr:'كارديو مكثف يحرق سعرات كتير في وقت قصير.',
      descEn:'High-intensity cardio that burns a lot of calories fast.',
      stepsAr:['امسك طرفي الحبل وابدأ بالقفز الخفيف','حافظ على معصمين ثابتين والقفز بالكاحل','استمر بإيقاع منتظم'],
      stepsEn:['Hold both handles and start with light hops','Keep wrists steady, jump from the ankles','Maintain a steady rhythm'],
      mistakesAr:'القفز العالي جدًا يرهق الركبتين.',
      mistakesEn:'Jumping too high strains the knees.',
      breathAr:'تنفس منتظم بإيقاع القفز — قصير وسريع من الفم.',
      breathEn:'Breathe steadily with the jumping rhythm — short and quick through the mouth.',
      altAr:'بديل: نط بدون حبل (تخيلي).', altEn:'Alt: imaginary jump rope (no rope).' },
  ],

  programs: [
    { id:'beginner-full-body', level:'beginner', goal:'general', days:3,
      ar:'مبتدئين - جسم كامل', en:'Beginner Full Body',
      descAr:'3 أيام أسبوعيًا لبناء أساس قوي وتعلم الحركات الصحيحة.',
      descEn:'3 days/week to build a strong foundation and learn proper form.',
      split:['bench-press','lat-pulldown','squat','plank'] },
    { id:'strength-upper-lower', level:'intermediate', goal:'strength', days:4,
      ar:'قوة - أعلى/أسفل', en:'Strength Upper/Lower',
      descAr:'4 أيام: يومين أعلى الجسم ويومين أسفل الجسم للتركيز على القوة.',
      descEn:'4 days: two upper-body, two lower-body sessions focused on strength.',
      split:['deadlift','ohp','squat','bent-row'] },
    { id:'hypertrophy-ppl', level:'intermediate', goal:'hypertrophy', days:6,
      ar:'تضخيم - Push Pull Legs', en:'Hypertrophy PPL',
      descAr:'6 أيام: دفع/سحب/رجل لتعظيم حجم العضلات.',
      descEn:'6 days: push/pull/legs split to maximize muscle growth.',
      split:['bench-press','ohp','lat-pulldown','bent-row','squat','leg-press'] },
    { id:'fatloss-circuit', level:'beginner', goal:'fatloss', days:4,
      ar:'حرق دهون - سيركت', en:'Fat Loss Circuit',
      descAr:'تمارين متتالية بأقل راحة لرفع معدل الحرق.',
      descEn:'Back-to-back circuits with minimal rest to boost calorie burn.',
      split:['jump-rope','squat','pushup','plank','treadmill'] },
    { id:'advanced-strength', level:'advanced', goal:'strength', days:5,
      ar:'محترفين - قوة قصوى', en:'Advanced Max Strength',
      descAr:'5 أيام لرفع الأرقام القصوى في الرفعات الأساسية.',
      descEn:'5 days to push your one-rep maxes on the big lifts.',
      split:['squat','deadlift','bench-press','ohp','bent-row'] },
    { id:'home-no-equip', level:'beginner', goal:'general', days:3,
      ar:'منزلي بدون جهاز', en:'Home / No Equipment',
      descAr:'تمارين وزن جسم بالكامل مناسبة للتدريب في المنزل.',
      descEn:'Fully bodyweight workouts great for training at home.',
      split:['pushup','lunges','plank','crunches','jump-rope'] },
  ],

  trainers: [
    { id:1, ar:'علاء شامل', en:'Alaa Shamel', specAr:'تضخيم عضلي', specEn:'Bodybuilding & Hypertrophy', years:6, image:'../images/alaa-shamel-card.jpg', fullImage:'../images/alaa-shamel-full.jpg' },
    { id:2, ar:'ياسمين عادل', en:'Yasmin Adel', specAr:'يوجا ومرونة', specEn:'Yoga & Flexibility', years:6 },
    { id:3, ar:'أحمد مصطفى', en:'Ahmed Mostafa', specAr:'كروسفيت وكارديو', specEn:'CrossFit & Cardio', years:5 },
    { id:4, ar:'سارة خالد', en:'Sara Khaled', specAr:'تغذية رياضية', specEn:'Sports Nutrition', years:7 },
    { id:5, ar:'كريم الشريف', en:'Kareem El-Sherif', specAr:'أثقال وقوة', specEn:'Strength & Powerlifting', years:8 },
    { id:6, ar:'نور حسام', en:'Nour Hossam', specAr:'لياقة عامة للسيدات', specEn:"Women's General Fitness", years:4 },
  ],

  plans: [
    { id:'basic', ar:'أساسية', en:'Basic', monthly:399, yearly:3990,
      featAr:['دخول صالة الأجهزة','خزانة يومية','استشارة تسجيل مجانية'],
      featEn:['Gym floor access','Daily locker','Free onboarding consult'] },
    { id:'premium', ar:'بريميوم', en:'Premium', monthly:699, yearly:6990, popular:true,
      featAr:['كل مميزات الأساسية','حصص جماعية غير محدودة','جلسة تدريب شخصي شهريًا','خطة تغذية مبدئية'],
      featEn:['Everything in Basic','Unlimited group classes','1 personal training session/month','Starter nutrition plan'] },
    { id:'vip', ar:'VIP', en:'VIP', monthly:1199, yearly:11990,
      featAr:['كل مميزات بريميوم','مدرب شخصي 8 جلسات/شهر','متابعة تغذية أسبوعية','دخول أي فرع في أي وقت'],
      featEn:['Everything in Premium','Personal trainer, 8 sessions/mo','Weekly nutrition follow-up','Access to any branch, anytime'] },
  ],

  schedule: [
    { dayAr:'السبت', dayEn:'Saturday', items:[
      { time:'08:00', ar:'كارديو صباحي', en:'Morning Cardio', trainer:3 },
      { time:'17:00', ar:'أثقال - مبتدئين', en:'Weights - Beginners', trainer:1 },
      { time:'19:00', ar:'يوجا', en:'Yoga', trainer:2 } ] },
    { dayAr:'الأحد', dayEn:'Sunday', items:[
      { time:'09:00', ar:'كروسفيت', en:'CrossFit', trainer:3 },
      { time:'18:00', ar:'تضخيم عضلي', en:'Bodybuilding', trainer:5 } ] },
    { dayAr:'الاثنين', dayEn:'Monday', items:[
      { time:'08:00', ar:'كارديو صباحي', en:'Morning Cardio', trainer:3 },
      { time:'17:00', ar:'لياقة سيدات', en:"Women's Fitness", trainer:6 },
      { time:'19:30', ar:'أثقال - متقدم', en:'Weights - Advanced', trainer:1 } ] },
    { dayAr:'الثلاثاء', dayEn:'Tuesday', items:[
      { time:'09:00', ar:'يوجا', en:'Yoga', trainer:2 },
      { time:'18:00', ar:'كروسفيت', en:'CrossFit', trainer:3 } ] },
    { dayAr:'الأربعاء', dayEn:'Wednesday', items:[
      { time:'08:00', ar:'كارديو صباحي', en:'Morning Cardio', trainer:3 },
      { time:'17:00', ar:'تضخيم عضلي', en:'Bodybuilding', trainer:5 },
      { time:'19:00', ar:'لياقة سيدات', en:"Women's Fitness", trainer:6 } ] },
    { dayAr:'الخميس', dayEn:'Thursday', items:[
      { time:'10:00', ar:'يوجا', en:'Yoga', trainer:2 },
      { time:'18:00', ar:'أثقال - مبتدئين', en:'Weights - Beginners', trainer:1 } ] },
    { dayAr:'الجمعة', dayEn:'Friday', items:[
      { time:'11:00', ar:'حصة عائلية مفتوحة', en:'Open Family Session', trainer:6 } ] },
  ],

  recipes: [
    { id:'oats-protein', ar:'شوفان بالبروتين والموز', en:'Protein Oats & Banana', kcal:380, protein:28, tag:'breakfast',
      ingAr:['نص كوب شوفان','ملعقة بروتين واي','موزة','ملعقة زبدة فول سوداني'],
      ingEn:['1/2 cup oats','1 scoop whey protein','1 banana','1 tbsp peanut butter'] },
    { id:'chicken-rice', ar:'صدور دجاج بالأرز والخضار', en:'Chicken, Rice & Veggies', kcal:520, protein:42, tag:'lunch',
      ingAr:['150 جم صدر دجاج مشوي','كوب أرز بني','خضار مشكل مشوي','ملعقة زيت زيتون'],
      ingEn:['150g grilled chicken breast','1 cup brown rice','Mixed grilled veggies','1 tbsp olive oil'] },
    { id:'tuna-salad', ar:'سلطة تونة عالية البروتين', en:'High-Protein Tuna Salad', kcal:310, protein:34, tag:'lunch',
      ingAr:['علبة تونة مصفاة','خس وطماطم وخيار','بيضة مسلوقة','ملعقة زيت زيتون وليمون'],
      ingEn:['1 can drained tuna','Lettuce, tomato, cucumber','1 boiled egg','1 tbsp olive oil & lemon'] },
    { id:'greek-yogurt-bowl', ar:'زبادي يوناني بالمكسرات والعسل', en:'Greek Yogurt & Nuts Bowl', kcal:260, protein:20, tag:'snack',
      ingAr:['كوب زبادي يوناني','ملعقة عسل','حفنة مكسرات مشكلة','فراولة مقطعة'],
      ingEn:['1 cup Greek yogurt','1 tbsp honey','A handful of mixed nuts','Sliced strawberries'] },
    { id:'salmon-potato', ar:'سلمون بالبطاطا الحلوة', en:'Salmon & Sweet Potato', kcal:560, protein:38, tag:'dinner',
      ingAr:['فيليه سلمون 150 جم','بطاطا حلوة متوسطة','سبانخ مشوي','ملعقة زيت زيتون'],
      ingEn:['150g salmon fillet','1 medium sweet potato','Sautéed spinach','1 tbsp olive oil'] },
    { id:'egg-whites-toast', ar:'بياض بيض بالتوست الأسمر', en:'Egg Whites & Whole Wheat Toast', kcal:290, protein:26, tag:'breakfast',
      ingAr:['5 بياض بيض','شريحتين توست أسمر','نص أفوكادو','رشة ملح وفلفل أسود'],
      ingEn:['5 egg whites','2 slices whole wheat toast','1/2 avocado','Salt & pepper to taste'] },
  ],

  faq: [
    { ar:'هل محتاج خبرة سابقة عشان أشترك؟', en:'Do I need prior experience to join?',
      aAr:'أبدًا. عندنا خطط وبرامج مخصصة للمبتدئين تمامًا، ومدربينا هيشرحولك كل حركة خطوة بخطوة.',
      aEn:'Not at all. We have plans and programs designed for complete beginners, and our trainers will walk you through every movement.' },
    { ar:'إزاي بيشتغل تحليل صورة الأكل؟', en:'How does the food photo analyzer work?',
      aAr:'بترفع صورة للأكل بتاعك، والموقع بيبعتها لخدمة تحليل صور ذكاء اصطناعي وترجعلك السعرات والمكونات التقريبية مباشرة في المتصفح.',
      aEn:'You upload a photo of your meal, and the site sends it to an AI image-analysis service that returns estimated calories and ingredients right in your browser.' },
    { ar:'بياناتي وتقدمي هل بيتحفظ فين؟', en:'Where is my data and progress stored?',
      aAr:'كل بياناتك (تقدم، حساب، تفضيلات) بتتحفظ محليًا في متصفحك (localStorage)، يعني محدش تاني بيشوفها.',
      aEn:'All your data (progress, account, preferences) is stored locally in your browser (localStorage), so no one else can see it.' },
    { ar:'ممكن ألغي أو أغيّر خطة الاشتراك؟', en:'Can I cancel or change my plan?',
      aAr:'أكيد، تقدر تغيّر أو تلغي في أي وقت من صفحة حسابك أو بزيارة الفرع.',
      aEn:'Sure — you can change or cancel anytime from your account page or by visiting the branch.' },
    { ar:'فيه تمارين أقدر أعملها من غير جيم؟', en:'Are there exercises I can do without a gym?',
      aAr:'أيوه، مكتبة التمارين فيها فلتر "بدون جهاز" وكمان عندنا برنامج منزلي كامل جاهز.', 
      aEn:'Yes — the exercise library has a "no equipment" filter, and we have a full ready-made home program too.' },
  ],
};
